- config: shared-flags
  flags:
    h_in: 50
    w_in: 50
    min_size: 6
    ch_in_0: 1
    ch_out_0:
      - 64
    f_1: "2**x"
    f_2: "2**(-x)"
    c_layers_up: 3
    # c_layers_down: [1,2]
    c_size: 3
    c_stride: 1
    c_padd: 1
    c_num:
      - 1
      - 3
    p_type: "max"
    p_size: 3
    p_stride: 2
    p_padd: 1
    classifier: 
      - "[[2048,2]]"
      # - "[[2048,1],[1024,1]]"
      # - "[[1024,1],[2048,1]]"
      - "[[2048,1],[512,2]]"
      # - "[[2048,1],[1024,2],[126,1]]"
      # - "[[2048,2],[1024,2],[126,1]]"
    num_classes: 32
    learning_rate: 1e-2
    epoch: 500
    batch_size: [16,32,64]


- model: DynamicCNN
  operations:
    train: 
      # requires:
        #- file: 
        #  target-type: copy
        #- exclude:
        #    dir: 
      # description: Train model
      main: /home/guest1/Folder/cifre_rotate/DynamicCNN_rotated2
      flags:
        $include: shared-flags
      flags-dest: args
      output-scalars:
        step: 'epoch: (\step)'
        Train_Loss: 'loss: (\value)'
        Train_Acc: 'train_accuracy: (\value)'
        Valid_Acc: 'valid_accuracy: (\value)'
      objective:
        # minimize: Valid_Loss
        maximize: Valid_Acc
      default-max-trials: 10  
      optimizers: 
        gaussian:
          default: yes
          random-starts: 3
          callsbaks: callbacks.DeltaYStopper(0.005, n_best=5)
        forest:
          default: no
          random-starts: 3
          callsbaks: callbacks.DeltaYStopper(0.005, n_best=5)
          






